MCU = RP2040
BOOTLOADER = rp2040

VIA_ENABLE = yes
VIAL_ENABLE = yes

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
EXTRAKEY_ENABLE = yes

# SPEGNIAMO L'OLED UFFICIALE (lasciamo fare al tuo codice manuale!)
OLED_ENABLE = no

COMBO_ENABLE = no
TAP_DANCE_ENABLE = no
KEY_OVERRIDE_ENABLE = no